/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#360f00",
        "surface-bright": "#faf8ff",
        "surface": "#faf8ff",
        "on-secondary-fixed-variant": "#005236",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-container": "#ffede6",
        "tertiary-fixed": "#ffdbcd",
        "on-tertiary-fixed-variant": "#7d2d00",
        "primary": "#004ac6",
        "on-secondary-container": "#00714d",
        "secondary": "#006c49",
        "surface-variant": "#e1e2ed",
        "surface-container-high": "#e7e7f3",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline": "#737686",
        "background": "#faf8ff",
        "error-container": "#ffdad6",
        "secondary-container": "#6cf8bb",
        "surface-container-highest": "#e1e2ed",
        "on-secondary-fixed": "#002113",
        "surface-container-low": "#f3f3fe",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-container": "#eeefff",
        "on-background": "#191b23",
        "primary-fixed-dim": "#b4c5ff",
        "on-error": "#ffffff",
        "surface-dim": "#d9d9e5",
        "surface-container": "#ededf9",
        "secondary-fixed": "#6ffbbe",
        "tertiary": "#943700",
        "secondary-fixed-dim": "#4edea3",
        "surface-tint": "#0053db",
        "on-surface-variant": "#434655",
        "primary-fixed": "#dbe1ff",
        "primary-container": "#2563eb",
        "tertiary-fixed-dim": "#ffb596",
        "tertiary-container": "#bc4800",
        "on-primary-fixed": "#00174b",
        "on-surface": "#191b23",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3039",
        "inverse-on-surface": "#f0f0fb",
        "on-secondary": "#ffffff",
        "outline-variant": "#c3c6d7",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "md": "16px",
        "xs": "4px",
        "2xl": "48px",
        "container-padding": "24px",
        "lg": "24px",
        "sm": "8px",
        "xl": "32px",
        "base": "4px",
        "stack-gap": "12px",
      },
      fontFamily: {
        "h1": ["Inter"],
        "label-md": ["Inter"],
        "button": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "h2": ["Inter"],
      },
      fontSize: {
        "h1": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "button": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
